### ISSUE TITLE
Any way to reduce object size / complexity?

### ISSUE THREAD

**Issue by edent** [tapio/obj-magic#1]
Just wanted to say how handy I found this tool. Surprised at just how quick it was.

Do you know of any way to reduce the number of faces a model has? For example, if I use `--scale 0.1` it would be nice to have the file size similarly reduced.

Thanks!

**Comment by tapio** [comment]
Automatic mesh simplification is a complex topic that's not easy to get right as sometimes there is no clean way to automatically reduce anything and still capture the shape accurately. It's also something that greatly benefits from a more graphical workflow as you really need to experiment with the parameters to get acceptable results (see e.g. Blender's Decimate modifier or perhaps https://github.com/wjakob/instant-meshes). Scaling is not where I'd attach it anyway, as I often need scaling just to match the object's size to my world without modifying the actual geometry.

Something that's on my TODO, but not a high priority is an "optimizer" that would reduce the file size by deduplicating position/texcoord/normal data that is shared between many vertices as well as rearranging material groups etc. more optimally. However, there's already tools for that, e.g. https://github.com/jonnenauha/obj-simplify

So yeah, would be a cool option and interesting to research and implement, but probably not something I have time to venture into.
